/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iFrame;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import dao.*;
import Classes.*;

/**
 *
 * @author eldi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public Main() {
        initComponents();
        this.panelAltCliente.setVisible(false);
        this.panelAltCarro.setVisible(false);
        this.panelCadCarro.setVisible(false);
        this.panelCadCliente.setVisible(false);
        this.panelReserva.setVisible(false);
        
        TabelaClientes();
        TabelaCarros();
        TabelaReserva();
        boxClientes();
        boxCarros();
        
    }
    
    /*Preenche JTable da Window AlteraCliente com os Clientes Cadastrados */
    public void TabelaClientes(){
        DefaultTableModel modelo = (DefaultTableModel) TableCliente.getModel();
        modelo.setNumRows(0);
        ClienteDao dao = new ClienteDao();
        
        for(Cliente list: dao.select() ){
            modelo.addRow(new Object[]{
                list.getNome(),
                list.getCpf(),
                list.getEndereco()
            });
        }
    }
    
    /*Preenche JTable da Window AlteraCarros com os Carros Cadastrados */
    public void TabelaCarros(){
        DefaultTableModel modelo = (DefaultTableModel) TableCarro.getModel();
        modelo.setNumRows(0);
        CarroDao dao = new CarroDao();
        for(Carro list: dao.select() ){
            modelo.addRow(new Object[]{
                list.getPlaca(),
                list.getModelo()
            });
        }
    }
    
    /*Preenche JTable da Window Reservas com os Reservas Cadastradas */
    public void TabelaReserva(){
        DefaultTableModel modelo = (DefaultTableModel) TabelaReserva.getModel();
        modelo.setNumRows(0);
        ReservaDao dao = new ReservaDao();
        for(Reserva list: dao.select() ){
            
            modelo.addRow(new Object[]{
                list.getClienteCPF(),
                list.getCarPLACA()
            });
        }
    }
    
    /*Preenche ComboBox da Window Reservas com os Clientes Cadastrados */
    public void boxClientes(){
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) boxCliente.getModel();
        modelo1.removeAllElements();
        ClienteDao cdao = new ClienteDao();

        for(Cliente list: cdao.select() ){
            modelo1.addElement(list.getCpf()+ ">" + list.getNome());
        }

    }
    
    /*Preenche ComboBox da Window Reservas com os Carros Cadastrados */
    public void boxCarros(){
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) boxCarro.getModel();
        modelo1.removeAllElements();
        CarroDao cdao = new CarroDao();

        for(Carro list: cdao.select() ){
            modelo1.addElement(list.getPlaca());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCadCarro = new javax.swing.JPanel();
        fModelCarro = new javax.swing.JTextField();
        fPlacaCarro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SalvarCadastroCarro = new javax.swing.JButton();
        LimparCadastroCarro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelAltCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fEnderecoCliente1 = new javax.swing.JTextField();
        fCPFCliente1 = new javax.swing.JTextField();
        fNomeCliente1 = new javax.swing.JTextField();
        SalvarAlteracaoCliente = new javax.swing.JButton();
        panelCadCliente = new javax.swing.JPanel();
        fNomeCliente = new javax.swing.JTextField();
        fCPFCliente = new javax.swing.JTextField();
        fEnderecoCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SalvarCadastroCliente = new javax.swing.JButton();
        LimparCadastroCliente = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelAltCarro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCarro = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fPlacaCarro1 = new javax.swing.JTextField();
        fModelCarro1 = new javax.swing.JTextField();
        SalvarAlteracaoCarro = new javax.swing.JButton();
        panelReserva = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaReserva = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        SalvarReserva = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        boxCliente = new javax.swing.JComboBox<>();
        boxCarro = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastroCarro = new javax.swing.JMenuItem();
        CadastroCliente = new javax.swing.JMenuItem();
        Reserva = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AlteraCarro = new javax.swing.JMenuItem();
        AlteraCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aluga Carro");
        setMaximumSize(new java.awt.Dimension(350, 600));

        jLabel5.setText("Modelo");

        jLabel6.setText("Placa");

        SalvarCadastroCarro.setText("SALVAR");
        SalvarCadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarCadastroCarroActionPerformed(evt);
            }
        });

        LimparCadastroCarro.setText("LIMPAR");
        LimparCadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCadastroCarroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CADASTRO DE CARRO");

        javax.swing.GroupLayout panelCadCarroLayout = new javax.swing.GroupLayout(panelCadCarro);
        panelCadCarro.setLayout(panelCadCarroLayout);
        panelCadCarroLayout.setHorizontalGroup(
            panelCadCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadCarroLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(SalvarCadastroCarro)
                .addGap(61, 61, 61)
                .addComponent(LimparCadastroCarro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadCarroLayout.createSequentialGroup()
                .addGroup(panelCadCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCadCarroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fModelCarro))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadCarroLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadCarroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCadCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fPlacaCarro)
                            .addGroup(panelCadCarroLayout.createSequentialGroup()
                                .addGroup(panelCadCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(0, 532, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelCadCarroLayout.setVerticalGroup(
            panelCadCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadCarroLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fModelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(fPlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(panelCadCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarCadastroCarro)
                    .addComponent(LimparCadastroCarro))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCliente);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ALTERAÇÃO DE CLIENTE");

        jLabel7.setText("Nome");

        jLabel9.setText("CPF");

        jLabel10.setText("Endereço");

        SalvarAlteracaoCliente.setText("Salvar");
        SalvarAlteracaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarAlteracaoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAltClienteLayout = new javax.swing.GroupLayout(panelAltCliente);
        panelAltCliente.setLayout(panelAltClienteLayout);
        panelAltClienteLayout.setHorizontalGroup(
            panelAltClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAltClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltClienteLayout.createSequentialGroup()
                        .addGroup(panelAltClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(fNomeCliente1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fCPFCliente1)
                            .addComponent(fEnderecoCliente1)
                            .addGroup(panelAltClienteLayout.createSequentialGroup()
                                .addGroup(panelAltClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SalvarAlteracaoCliente)
                        .addGap(252, 252, 252))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        panelAltClienteLayout.setVerticalGroup(
            panelAltClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltClienteLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(fNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addComponent(fCPFCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fEnderecoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SalvarAlteracaoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jLabel3.setText("Endereço");

        SalvarCadastroCliente.setText("SALVAR");
        SalvarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarCadastroClienteActionPerformed(evt);
            }
        });

        LimparCadastroCliente.setText("LIMPAR");
        LimparCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCadastroClienteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CADASTRO DE CLIENTE");

        javax.swing.GroupLayout panelCadClienteLayout = new javax.swing.GroupLayout(panelCadCliente);
        panelCadCliente.setLayout(panelCadClienteLayout);
        panelCadClienteLayout.setHorizontalGroup(
            panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fCPFCliente)
                    .addComponent(fEnderecoCliente)
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadClienteLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(SalvarCadastroCliente)
                                .addGap(61, 61, 61)
                                .addComponent(LimparCadastroCliente))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadClienteLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        panelCadClienteLayout.setVerticalGroup(
            panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(fCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarCadastroCliente)
                    .addComponent(LimparCadastroCliente))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        TableCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Placa", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCarroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableCarro);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ALTERAÇÃO DE CARRO");

        jLabel12.setText("Placa");

        jLabel13.setText("Modelo");

        SalvarAlteracaoCarro.setText("SALVAR");
        SalvarAlteracaoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarAlteracaoCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAltCarroLayout = new javax.swing.GroupLayout(panelAltCarro);
        panelAltCarro.setLayout(panelAltCarroLayout);
        panelAltCarroLayout.setHorizontalGroup(
            panelAltCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltCarroLayout.createSequentialGroup()
                .addGroup(panelAltCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltCarroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAltCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fModelCarro1)
                            .addComponent(fPlacaCarro1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAltCarroLayout.createSequentialGroup()
                                .addGroup(panelAltCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelAltCarroLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(SalvarAlteracaoCarro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAltCarroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltCarroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        panelAltCarroLayout.setVerticalGroup(
            panelAltCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fModelCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(5, 5, 5)
                .addComponent(fPlacaCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalvarAlteracaoCarro)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        TabelaReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "PLACA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TabelaReserva);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Reserva");

        jLabel17.setText("Cliente");

        SalvarReserva.setText("SALVAR");
        SalvarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarReservaActionPerformed(evt);
            }
        });

        jLabel18.setText("Carro");

        javax.swing.GroupLayout panelReservaLayout = new javax.swing.GroupLayout(panelReserva);
        panelReserva.setLayout(panelReservaLayout);
        panelReservaLayout.setHorizontalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservaLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(117, 117, 117))
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(SalvarReserva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReservaLayout.setVerticalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(0, 0, 0)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(SalvarReserva)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        CadastroCarro.setText("Carro");
        CadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCarroActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroCarro);

        CadastroCliente.setText("Cliente");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroCliente);

        Reserva.setText("Reserva");
        Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaActionPerformed(evt);
            }
        });
        jMenu1.add(Reserva);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alteração");

        AlteraCarro.setText("Carro");
        AlteraCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlteraCarroActionPerformed(evt);
            }
        });
        jMenu2.add(AlteraCarro);

        AlteraCliente.setText("Cliente");
        AlteraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlteraClienteActionPerformed(evt);
            }
        });
        jMenu2.add(AlteraCliente);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCadCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAltCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAltCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCadCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAltCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAltCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        // TODO add your handling code here:
        System.out.println("CARRO");
        this.panelCadCarro.setVisible(false);
        this.panelCadCliente.setVisible(true);
        
        this.panelAltCliente.setVisible(false);
        this.panelAltCarro.setVisible(false);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCarroActionPerformed
        // TODO add your handling code here:
        this.panelCadCarro.setVisible(true);
        this.panelCadCliente.setVisible(false);
        
        this.panelAltCliente.setVisible(false);
        this.panelAltCarro.setVisible(false);
        
        this.panelReserva.setVisible(false);
    }//GEN-LAST:event_CadastroCarroActionPerformed

    private void AlteraCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlteraCarroActionPerformed
        // TODO add your handling code here:
        this.panelAltCliente.setVisible(false);
        this.panelAltCarro.setVisible(true);
        
        this.panelCadCarro.setVisible(false);
        this.panelCadCliente.setVisible(false);
        
        this.panelReserva.setVisible(false);
               TabelaCarros();

    }//GEN-LAST:event_AlteraCarroActionPerformed

    private void AlteraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlteraClienteActionPerformed
        // TODO add your handling code here:
        this.panelAltCliente.setVisible(true);
        this.panelAltCarro.setVisible(false);
        
        this.panelCadCarro.setVisible(false);
        this.panelCadCliente.setVisible(false);
        
        this.panelReserva.setVisible(false);
        TabelaClientes();
 
    }//GEN-LAST:event_AlteraClienteActionPerformed

    private void SalvarAlteracaoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarAlteracaoCarroActionPerformed
        // TODO add your handling code here:
        Carro ca = new Carro(fPlacaCarro1.getText(), fModelCarro1.getText());
        CarroDao caDao = new CarroDao();
        
        caDao.update(ca);
        TabelaCarros();
    }//GEN-LAST:event_SalvarAlteracaoCarroActionPerformed

    private void SalvarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarReservaActionPerformed
        // TODO add your handling code here:
        String chave[] = new String[2];
        chave = boxCliente.getSelectedItem().toString().split(">");
        System.out.println(chave[0]);
        Reserva re = new Reserva(chave[0].toString(),boxCarro.getSelectedItem().toString());
        ReservaDao reDao = new ReservaDao();
        
        reDao.create(re);
        TabelaReserva();
        
        
    }//GEN-LAST:event_SalvarReservaActionPerformed

    private void ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaActionPerformed
        // TODO add your handling code here:
        this.panelReserva.setVisible(true);
        
        this.panelAltCliente.setVisible(false);
        this.panelAltCarro.setVisible(false);
        
        this.panelCadCarro.setVisible(false);
        this.panelCadCliente.setVisible(false);
        
        TabelaReserva();
        boxClientes();
        boxCarros();
    }//GEN-LAST:event_ReservaActionPerformed

    private void TableCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCarroMouseClicked
        // TODO add your handling code here:
        if(TableCarro.getSelectedRow() != -1){
           fPlacaCarro1.setText(TableCarro.getValueAt(TableCarro.getSelectedRow(),0).toString());
           fModelCarro1.setText(TableCarro.getValueAt(TableCarro.getSelectedRow(),1).toString());
        }
    }//GEN-LAST:event_TableCarroMouseClicked

    private void SalvarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarCadastroClienteActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente(fNomeCliente.getText(), fCPFCliente.getText(),fEnderecoCliente.getText());
        ClienteDao cDao = new ClienteDao();
        
        cDao.create(c);
        
    }//GEN-LAST:event_SalvarCadastroClienteActionPerformed

    private void LimparCadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCadastroCarroActionPerformed
        // TODO add your handling code here:
        fModelCarro.setText("");
        fPlacaCarro.setText("");
    }//GEN-LAST:event_LimparCadastroCarroActionPerformed

    private void LimparCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCadastroClienteActionPerformed
        // TODO add your handling code here:
        fNomeCliente.setText("");
        fCPFCliente.setText("");
        fEnderecoCliente.setText("");
    }//GEN-LAST:event_LimparCadastroClienteActionPerformed

    private void SalvarCadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarCadastroCarroActionPerformed
        // TODO add your handling code here:
        Carro ca = new Carro(fPlacaCarro.getText(), fModelCarro.getText());
        CarroDao caDao = new CarroDao();
        
        caDao.create(ca);
        
    }//GEN-LAST:event_SalvarCadastroCarroActionPerformed

    private void SalvarAlteracaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarAlteracaoClienteActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente(fNomeCliente1.getText(), fCPFCliente1.getText(), fEnderecoCliente1.getText());
        ClienteDao cDao = new ClienteDao();
        
        cDao.update(c);
        TabelaClientes();
    }//GEN-LAST:event_SalvarAlteracaoClienteActionPerformed

    private void TableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClienteMouseClicked
        // TODO add your handling code here:
        if(TableCliente.getSelectedRow() != -1){
           fNomeCliente1.setText(TableCliente.getValueAt(TableCliente.getSelectedRow(),0).toString());
           fCPFCliente1.setText(TableCliente.getValueAt(TableCliente.getSelectedRow(),1).toString());
           fEnderecoCliente1.setText(TableCliente.getValueAt(TableCliente.getSelectedRow(),2).toString());
        }
    }//GEN-LAST:event_TableClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlteraCarro;
    private javax.swing.JMenuItem AlteraCliente;
    private javax.swing.JMenuItem CadastroCarro;
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JButton LimparCadastroCarro;
    private javax.swing.JButton LimparCadastroCliente;
    private javax.swing.JMenuItem Reserva;
    private javax.swing.JButton SalvarAlteracaoCarro;
    private javax.swing.JButton SalvarAlteracaoCliente;
    private javax.swing.JButton SalvarCadastroCarro;
    private javax.swing.JButton SalvarCadastroCliente;
    private javax.swing.JButton SalvarReserva;
    private javax.swing.JTable TabelaReserva;
    private javax.swing.JTable TableCarro;
    private javax.swing.JTable TableCliente;
    private javax.swing.JComboBox<String> boxCarro;
    private javax.swing.JComboBox<String> boxCliente;
    private javax.swing.JTextField fCPFCliente;
    private javax.swing.JTextField fCPFCliente1;
    private javax.swing.JTextField fEnderecoCliente;
    private javax.swing.JTextField fEnderecoCliente1;
    private javax.swing.JTextField fModelCarro;
    private javax.swing.JTextField fModelCarro1;
    private javax.swing.JTextField fNomeCliente;
    private javax.swing.JTextField fNomeCliente1;
    private javax.swing.JTextField fPlacaCarro;
    private javax.swing.JTextField fPlacaCarro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelAltCarro;
    private javax.swing.JPanel panelAltCliente;
    private javax.swing.JPanel panelCadCarro;
    private javax.swing.JPanel panelCadCliente;
    private javax.swing.JPanel panelReserva;
    // End of variables declaration//GEN-END:variables
}
